<table class="patient_table">
    <thead>
        <tr>
            <th>NHS Number</th>
            <th>Date of Birth</th>
            <th>Ward</th>
            <th>Speciality</th>
            <th class="tail" title="Related Infections">Inf</th>
            <th class="tail" title="Related Infections in Patients that have shared a ward with this patient">Inf & Ovl</th>
        </tr>
    </thead>
    <tbody>

    </tbody>
</table>
